apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: as-users-api
  namespace: default
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: as-users-api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
