apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: as-users-api
  namespace: default
  labels:
    release: stable
spec:
  namespaceSelector:
    matchNames:
       - default
  selector:
    matchLabels:
      app: as-users-api
  endpoints:
<<<<<<<< HEAD:users-api-monitor.yaml
    - port: http
      path: /metrics
      interval: 10s
========
  - port: http
    path: /metrics
    interval: 10s
>>>>>>>> 4438e382b50690236fe408ffbdd8cce4721f0101:k8s/users-api-monitoring.yaml
